admin_pages/urls.py
from django.urls import path, include
from . import views

app_name='admin_pages'

urlpatterns = [
    path('', views.admin_index, name='admin_index'),
    path('manage_site_look', views.manage_site_look, name='manage_site_look'),
    path('manage_home', views.manage_home, name='manage_home'),
    path('manage_users', views.manage_users, name='manage_users'),
    path('manage_user_profile', views.manage_user_profile, name='manage_user_profile'),

    # Metrics
    path('manage_pet_sales_opts', views.manage_pet_sales_opts, name='manage_pet_sales_opts'),
    path('manage_product_sales_opts', views.manage_product_sales_opts, name='manage_product_sales_opts'),
    path('manage_site_visits_opts', views.manage_site_visits_opts, name='manage_site_visits_opts'),
    path('manage_pages_viewed_opts', views.manage_pages_viewed_opts, name='manage_pages_viewed_opts'),
    path('manage_users_opts', views.manage_users_opts, name='manage_users_opts'),
    path('manage_day_and_time_opts', views.manage_day_and_time_opts, name='manage_day_and_time_opts'),
]

dashboard/urls.py
from django.contrib import admin
from django.contrib.auth import login, views as auth_views
from django.urls import path, include, reverse_lazy
from django.views.generic.base import TemplateView
from admin_pages import views as admin_views

urlpatterns = [
    path('', include('site_pages.urls')),
    path('admin_pages/', include('admin_pages.urls')),
    path('login/', auth_views.LoginView.as_view(
        	template_name='users/login.html'), name='login'),
    path('accounts/login/', auth_views.LoginView.as_view(
        	template_name='users/login.html'), name='login'),
    path('users/', include('users.urls')),
    path('robots.txt', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
]

site_pages/urls.py
from django.urls import path, include
from . import views

app_name='site_pages'

urlpatterns = [
    path('', views.index, name='index'),
]

users/urls.py
"""Defines url patterns for the users app."""

from django.urls import path, reverse, reverse_lazy
from django.contrib.auth import login, views as auth_views
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(
        	template_name='users/login.html'), name='login'),
	path('logout/', views.logout_view, name='logout'),
	path('register/', views.register, name='register'),
	path('update_user/', views.update_user, name='update_user'),
	path('confirm_delete_user/<int:user_id>', views.confirm_delete_user, name='confirm_delete_user'),
	path('delete_user/<int:user_id>', views.delete_user, name='delete_user'),

	path('reset_password/', auth_views.PasswordResetView.as_view(
			template_name='users/reset_password_email.html',
			email_template_name='users/reset_email_message.html',
			success_url=reverse_lazy('users:password_reset_complete'),
		), name='reset_password'),
	
	path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(
			template_name='users/reset_password_sent.html'), name='password_reset_done'),
	
	path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
			template_name='users/reset_password_confirm.html',
			success_url=reverse_lazy('users:password_reset_complete')
			), name='password_reset_confirm'),
	
	path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(
			template_name='users/reset_password_complete.html'), name='password_reset_complete')
]

site_pages/models.py
from django.db import models

class Home(models.Model):
    """Contains attributes that determine the content of the home page."""
    title          = models.CharField(max_length=60, blank=True, null=True, default='Pet Shop Metrics')
    alert_banner   = models.CharField(max_length=300, blank=True, null=True, default='')
    about_descr    = models.CharField(max_length=400, blank=True, null=True, default='')

site_pages/forms.py
from django import forms
from .models import *

class HomeForm(forms.ModelForm):
    title = forms.CharField(
        label='Title',
        required=False,
    )
    alert_banner = forms.CharField(
        label='Alert Banner:',
        required=False,
    )
    about_descr = forms.CharField(
        label='About Description',
        required=False,
        widget=forms.Textarea(attrs={
            'placeholder': 'Describe the Pet Shop dashboard.',
            'rows': 3,
            'cols': 15,
        })
    )

    class Meta:
        model = Home
        fields = [ 'title', 'alert_banner', 'about_descr' ]

site_pages/views.py
from django.shortcuts import render

from dashboard import settings
from .models import *
from .forms import *
from admin_pages.models import *

from . import data_aggregator

def index(request):
    """Displays the landing page.
    Parameters:
    request (HttpRequest): An HTTP Request object. 
    Returns:
    HttpResponse: Directs the user to the landing page.
    """
    home = Home.objects.get(id=1)
    petSalesOpts = PetSalesOpts.objects.get(id=1)
    productSalesOpts = ProductSalesOpts.objects.get(id=1)
    siteVisitsOpts = SiteVisitsOpts.objects.get(id=1)
    pagesViewedOpts = PagesViewedOpts.objects.get(id=1)
    usersOpts = UsersOpts.objects.get(id=1)
    dayAndTimeOpts = DayAndTimeOpts.objects.get(id=1)

    pet_categories_list, pet_categories_values_list = (data_aggregator
        .get_pet_sales_categories(petSalesOpts.timerange, petSalesOpts.top_num_categories))

    pet_breeds_list, pet_breeds_values_list = (data_aggregator
        .get_pet_sales_breeds(petSalesOpts.timerange, petSalesOpts.top_num_breeds))

    product_sales_list, product_sales_values_list = (data_aggregator
        .get_product_sales(productSalesOpts.timerange, productSalesOpts.top_num_products))

    if siteVisitsOpts.display_type == 0: # Get per region
        site_visits_list, site_visits_values_list = (data_aggregator
        .get_site_visits_region(siteVisitsOpts.timerange, siteVisitsOpts.top_num_by_location))

        site_visits_display_type = 'regions'
    else: # Get per country
        site_visits_list, site_visits_values_list = (data_aggregator
        .get_site_visits_country(siteVisitsOpts.timerange, siteVisitsOpts.top_num_by_location))

        site_visits_display_type = 'countries'

    page_views_list, page_views_values_list = (data_aggregator
            .get_page_views(pagesViewedOpts.timerange, pagesViewedOpts.top_num_pages))

    users_registered_count, users_online_count = data_aggregator.get_users_metrics()

    site_visits = data_aggregator.get_site_visits_datetimes(dayAndTimeOpts.timerange, dayAndTimeOpts.top_num_days)

    context = {
        'home': home,
        'petSalesOpts': petSalesOpts,
        'productSalesOpts': productSalesOpts,
        'siteVisitsOpts': siteVisitsOpts,
        'pagesViewedOpts': pagesViewedOpts,
        'usersOpts': usersOpts,
        'dayAndTimeOpts': dayAndTimeOpts,
        
        'pet_categories_list': pet_categories_list,
        'pet_categories_values_list': pet_categories_values_list,

        'pet_breeds_list': pet_breeds_list,
        'pet_breeds_values_list': pet_breeds_values_list,
		
		'product_sales_list': product_sales_list,
		'product_sales_values_list': product_sales_values_list,
		
		'site_visits_list': site_visits_list,
		'site_visits_values_list': site_visits_values_list,
        'site_visits_display_type': site_visits_display_type,
        'site_visits': site_visits,
		
		'page_views_list': page_views_list,
		'page_views_values_list': page_views_values_list,

        'users_registered_count': users_registered_count,
        'users_online_count': users_online_count,        
    }
    return render(request, 'site_pages/index.html', context)

templates/site_pages/site_pages_base.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
  <title>Pet Shop Dashboard: {% block page_title %}{% endblock page_title %}</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="author" content="CSCI-4350-002: Team Ducks">

  {{ font|safe }}
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="icon" href="{% static 'images/favicon.ico' %}">

  <script
  src="https://code.jquery.com/jquery-3.5.1.min.js"
  integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
  crossorigin="anonymous"></script>
  <script 
  src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
  integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
  crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
  integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
  crossorigin="anonymous"></script>
  {% block morelinks %}{% endblock morelinks %}

  <style>
    footer { background-color: #448980; }
    .nav-link { border-radius: 4px; }
  </style>

  {% block head_scripts %}
  {% endblock head_scripts %}
</head>
<body class="site_pages">
    {% if user.is_authenticated %}
    <div class="text-center">
    <a class="text-dark nav-link" href="{% url 'admin_pages:admin_index' %}"
        style="background-color: #FFD9AB; font-weight: bold;">
        MANAGE
    </a>
    </div>
    {% endif %}
    {% block content %}{% endblock content %}
    <footer class="shadow text-light" id="footer">
        Copyright <a href="{% url 'login' %}" style="text-decoration: none; color: #F8F9FA;"> &copy;</a>
        &nbsp;2021 - Team Ducks
    </footer>
</body>