admin_pages/urls.py
from django.urls import path, include
from . import views

app_name='admin_pages'

urlpatterns = [
    path('', views.admin_index, name='admin_index'),
    path('manage_site_look', views.manage_site_look, name='manage_site_look'),
    path('manage_home', views.manage_home, name='manage_home'),
    path('manage_users', views.manage_users, name='manage_users'),
    path('manage_user_profile', views.manage_user_profile, name='manage_user_profile'),

    # Metrics
    path('manage_pet_sales_opts', views.manage_pet_sales_opts, name='manage_pet_sales_opts'),
    path('manage_product_sales_opts', views.manage_product_sales_opts, name='manage_product_sales_opts'),
    path('manage_site_visits_opts', views.manage_site_visits_opts, name='manage_site_visits_opts'),
    path('manage_pages_viewed_opts', views.manage_pages_viewed_opts, name='manage_pages_viewed_opts'),
    path('manage_users_opts', views.manage_users_opts, name='manage_users_opts'),
    path('manage_day_and_time_opts', views.manage_day_and_time_opts, name='manage_day_and_time_opts'),
]

dashboard/urls.py
from django.contrib import admin
from django.contrib.auth import login, views as auth_views
from django.urls import path, include, reverse_lazy
from django.views.generic.base import TemplateView
from admin_pages import views as admin_views

urlpatterns = [
    path('', include('site_pages.urls')),
    path('admin_pages/', include('admin_pages.urls')),
    path('login/', auth_views.LoginView.as_view(
        	template_name='users/login.html'), name='login'),
    path('accounts/login/', auth_views.LoginView.as_view(
        	template_name='users/login.html'), name='login'),
    path('users/', include('users.urls')),
    path('robots.txt', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
]

site_pages/urls.py
from django.urls import path, include
from . import views

app_name='site_pages'

urlpatterns = [
    path('', views.index, name='index'),
]

users/urls.py
"""Defines url patterns for the users app."""

from django.urls import path, reverse, reverse_lazy
from django.contrib.auth import login, views as auth_views
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(
        	template_name='users/login.html'), name='login'),
	path('logout/', views.logout_view, name='logout'),
	path('register/', views.register, name='register'),
	path('update_user/', views.update_user, name='update_user'),
	path('confirm_delete_user/<int:user_id>', views.confirm_delete_user, name='confirm_delete_user'),
	path('delete_user/<int:user_id>', views.delete_user, name='delete_user'),

	path('reset_password/', auth_views.PasswordResetView.as_view(
			template_name='users/reset_password_email.html',
			email_template_name='users/reset_email_message.html',
			success_url=reverse_lazy('users:password_reset_complete'),
		), name='reset_password'),
	
	path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(
			template_name='users/reset_password_sent.html'), name='password_reset_done'),
	
	path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
			template_name='users/reset_password_confirm.html',
			success_url=reverse_lazy('users:password_reset_complete')
			), name='password_reset_confirm'),
	
	path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(
			template_name='users/reset_password_complete.html'), name='password_reset_complete')
]

admin_pages/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class SiteLook(models.Model):
    """Contains attributes that affect the appearance of the site."""
    navigation_img      = models.FileField()
    navigation_img_size = models.CharField(max_length=12, blank=True, null=True)

class UserProfile(models.Model):
    profile_img      = models.FileField(null=True, blank=True)
    profile_img_name = models.TextField(default='profile-default.gif')
    profile_role     = models.CharField(max_length=13, blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)


#################### Metrics:
# TODO: Implement each of these. These are the options that let us specify # of bins (e.g. top 5, top 10 most popular) and time range.

class PetSalesOpts(models.Model): # Most popular pets sold per unit of time
    top_num_categories = models.IntegerField(default=6)
    top_num_breeds = models.IntegerField(default=6)
    timerange = models.IntegerField(default=7)
    display = models.BooleanField(default=False)

class ProductSalesOpts(models.Model): # Most popular store products sold per unit of time
    top_num_products = models.IntegerField(default=6)
    timerange = models.IntegerField(default=7)
    display = models.BooleanField(default=False)

class SiteVisitsOpts(models.Model): # This is referring to the Session table -- [...]/monitoring/usage/visits
    top_num_by_location = models.IntegerField(default=6)
    display_type = models.IntegerField(default=0)
    timerange = models.IntegerField(default=7)
    display = models.BooleanField(default=False)

class PagesViewedOpts(models.Model): # Pages_Viewed table -- Most popular pages viewed per unit of time.
    top_num_pages = models.IntegerField(default=6)
    timerange = models.IntegerField(default=7)
    display = models.BooleanField(default=False)

class UsersOpts(models.Model): # No. users registered per unit of time, no. users online now
    timerange_registered = models.IntegerField(default=0)
    show_users_online = models.BooleanField(default=True)
    display = models.BooleanField(default=False)

class DayAndTimeOpts(models.Model): # Most popular days and times
    top_num_days = models.IntegerField(default=6)
    top_num_times = models.IntegerField(default=6)
    timerange = models.IntegerField(default=7)
    display = models.BooleanField(default=False)

admin_pages/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.core.files.storage import FileSystemStorage

from dashboard import settings
from site_pages.models import Home
from site_pages.forms import HomeForm
from .models import *
from .forms import *

import os


STATIC_DIR      = settings.STATIC_ROOT
ROBOTS_TXT_DIR  = settings.BASE_DIR + '/templates/'
STATIC_IMGS_DIR = STATIC_DIR + '/images/'
NAV_ICON_DIR    = STATIC_DIR + '/nav_image/'


def try_delete_files(path):
    """Attempts to delete all files in the directory, path.

    Parameters:
    path (string): the file path from which to remove all files.

    Returns:
    bool: Indicates whether all file deletions succeeded or not.
    """
    failure = False
    try:
        for root, dirs, files in os.walk(path):
            for f in files:
                try:
                    os.remove(os.path.join(root, f))
                except:
                    failure = True
        return failure
    except:
        return False


@login_required
def admin_index(request):
    user = request.user
    context = { 'current_user': user.first_name }

    return render(request, 'admin_pages/index.html', context)
  

@login_required
def manage_site_look(request):
    site_look = SiteLook.objects.get(id=1)

    if (request.method != 'POST'):
        form = SiteLookForm(instance=site_look)
    else:
        fs_storage = FileSystemStorage(location=NAV_ICON_DIR)
        form = SiteLookForm(instance=site_look, data=request.POST)

        if len(request.FILES) != 0:
            if 'navigation_img' in request.FILES.keys():
                try_delete_files(NAV_ICON_DIR)
                image = request.FILES['navigation_img']
                fs_storage.save('nav_image.png', image)
            
            if 'favicon' in request.FILES.keys():
                fs_storage = FileSystemStorage(location=STATIC_IMGS_DIR)
                try:
                    os.remove(os.path.join(STATIC_IMGS_DIR, 'favicon.ico'))
                except:
                    pass
                image = request.FILES['favicon']
                fs_storage.save('favicon.ico', image)

        if form.is_valid():
            form.save()
        
        return HttpResponseRedirect(reverse('admin_pages:admin_index'))
    
    context = { 'form': form }
    return render(request, 'admin_pages/manage_site_look/manage_site_look.html', context)


@login_required
def manage_home(request):
    home = Home.objects.get(id=1)
    if request.method != 'POST':
        form = HomeForm(instance=home)
    else:
        form = HomeForm(instance=home, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('admin_pages:admin_index'))
    context = { 'form': form }
    return render(request, 'admin_pages/manage_home/manage_home.html', context)


@login_required
def manage_user_profile(request):
    profile = UserProfile.objects.get(user=User.objects.get(id=request.user.id))
    if request.method != 'POST':
        form = UserProfileForm(instance=profile)
    else:
        form = UserProfileForm(instance=profile, data=request.POST)

        if form.is_valid():
            form.save()

            if len(request.FILES) != 0:
                fs_storage = FileSystemStorage(location=STATIC_IMGS_DIR)
                if ((profile.profile_img_name != '') 
                    and (profile.profile_img_name != 'profile-default.gif')): # Prevent deletion of default image.
                    try:
                        os.remove(os.path.join(STATIC_IMGS_DIR,
                            profile.profile_img_name))
                    except:
                        pass
                icon = request.FILES['profile_img']
                filename = fs_storage.save(icon.name, icon)
                profile.profile_img_name = filename
                profile.save()
            return HttpResponseRedirect(reverse('admin_pages:admin_index'))
    
    context = { 'profile': profile, 'form': form }
    return render(request, 'admin_pages/manage_user_profile/manage_user_profile.html',
                    context)


@login_required
def manage_users(request):
    """Provides the user a form template to facilitate creation and deletion of a
    User admin (ish) account. The user is considered an admin for access to the 
    Admin Pages and API but is not a true Django admin which is unnecessary since
    there are no admin-registered models.

    Parameters:
    request (HttpRequest): An HTTP Request object. 

    Returns:
    HttpResponse: Directs the user to the appropriate URL.
    """
    if request.user.is_staff:
        users = User.objects.all()

        context = { 'users': users }
        return render(request, 'admin_pages/manage_users/manage_users.html', context)
    else:
        return HttpResponseRedirect(reverse('admin_pages:admin_index'))

@login_required
def manage_pet_sales_opts(request):
    pet_sales_opts = PetSalesOpts.objects.get(id=1)
    if request.method != 'POST':
        form = PetSalesOptsForm(instance=pet_sales_opts)
    else:
        form = PetSalesOptsForm(instance=pet_sales_opts, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('admin_pages:admin_index'))
    context = { 'form': form }
    return render(request, 'admin_pages/manage_metrics_display_opts/manage_petsales.html', context)

@login_required
def manage_product_sales_opts(request):
    product_sales_opts = ProductSalesOpts.objects.get(id=1)
    if request.method != 'POST':
        form = ProductSalesOptsForm(instance=product_sales_opts)
    else:
        form = ProductSalesOptsForm(instance=product_sales_opts, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('admin_pages:admin_index'))
    context = { 'form': form } 
    return render(request, 'admin_pages/manage_metrics_display_opts/manage_productsales.html', context)

@login_required
def manage_site_visits_opts(request):
    site_visits_opts = SiteVisitsOpts.objects.get(id=1)
    if request.method != 'POST':
        form = SiteVisitsOptsForm(instance=site_visits_opts)
    else:
        form = SiteVisitsOptsForm(instance=site_visits_opts, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('admin_pages:admin_index'))
    context = { 'form': form } 
    return render(request, 'admin_pages/manage_metrics_display_opts/manage_sitevisits.html', context)

@login_required
def manage_pages_viewed_opts(request):
    pages_viewed_opts = PagesViewedOpts.objects.get(id=1)
    if request.method != 'POST':
        form = PagesViewedOptsForm(instance=pages_viewed_opts)
    else:
        form = PagesViewedOptsForm(instance=pages_viewed_opts, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('admin_pages:admin_index'))
    context = { 'form': form } 
    return render(request, 'admin_pages/manage_metrics_display_opts/manage_pagesviewed.html', context)

@login_required
def manage_users_opts(request):
    users_opts = UsersOpts.objects.get(id=1)
    if request.method != 'POST':
        form = UsersOptsForm(instance=users_opts)
    else:
        form = UsersOptsForm(instance=users_opts, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('admin_pages:admin_index'))
    context = { 'form': form } 
    return render(request, 'admin_pages/manage_metrics_display_opts/manage_users.html', context)

@login_required
def manage_day_and_time_opts(request):
    day_and_time_opts = DayAndTimeOpts.objects.get(id=1)
    if request.method != 'POST':
        form = DayAndTimeOptsForm(instance=day_and_time_opts)
    else:
        form = DayAndTimeOptsForm(instance=day_and_time_opts, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('admin_pages:admin_index'))
    context = { 'form': form }
    return render(request, 'admin_pages/manage_metrics_display_opts/manage_dayandtime.html', context)

templates/admin_pages/admin_pages_base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href='https://fonts.googleapis.com/css?family=Muli' rel='stylesheet'>
  <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" 
    integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous"> 
  <link rel="stylesheet" href="{% static 'admin_pages/css/font-awesome.min.css' %}"> 
  <link rel="stylesheet" href="{% static 'admin_pages/css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="icon" href="{% static 'images/favicon.ico' %}">
  {% block additional_links %}{% endblock additional_links %}
  <script src="https://code.jquery.com/jquery-3.5.1.min.js"
	  integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
	  crossorigin="anonymous">
  </script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
  integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
  crossorigin="anonymous">
  </script>
  {{ tinymce_script|safe }}
  <style>
    input[type="checkbox"] {
      width: 1rem;
      height: 1rem;
    }
    svg.bi {
      padding-right: 10px;
    }
    span.title{
        display: inline;
    }
    ul {
      list-style-type: none;
    }
  </style>
</head>

<body class="admin_pages" style="font-family: 'Muli', sans-serif;">
  <nav class="navbar navbar-expand-lg navbar-light bg-light static-top">
    <div class="container">
      <a class="navbar-brand" href="{% url 'site_pages:index' %}">
        {% load static %}
        <img src="{% static 'nav_image/nav_image.png' %}"
          alt="Navigation icon" style="{{ navigation_img_size }}">
      </a>
    </div>
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <div class="profile-dropdown">
          <div class="container">
            {% block profile_name_and_role %}
            {% endblock profile_name_and_role %}
          </div>
          <button class="profile-dropbtn" onclick="toggleDropdown()" style="padding: %; border-radius: 5px;">
            <img src="/static/images/{{ profile.profile_img_name }}"
            alt="Profile Image" width="90px;" height="90px;" style="border-radius: 3px;">
          </button>
          <div class="profile-dropdown-content" id="profile-dropdown-content" style="padding: 5%;">
            {% block profile_dropdown_links %}
            {% endblock profile_dropdown_links %}
            <a href="{% url 'users:logout' %}">Logout</a>
          </div>
      </li>
    </ul>
  </nav>
  <div class="text-center">
    <a class="text-dark nav-link" href="{% url 'site_pages:index' %}"
        style="background-color: #FFD9AB; font-weight: bold;">
        VIEW METRICS HOME
    </a>
  </div>
{% block content %} {% endblock content %}
  <script>
    function toggleDropdown() {
      document.getElementById("profile-dropdown-content").classList.toggle("show");
    }

    // Close the dropdown menu if the user clicks outside of it
    window.onclick = function(event) {
      if (!event.target.matches('.dropbtn')) {
        var dropdowns = document.getElementsByClassName("dropdown-content");
        var i;
        for (i = 0; i < dropdowns.length; i++) {
          var openDropdown = dropdowns[i];
          if (openDropdown.classList.contains('show')) {
            openDropdown.classList.remove('show');
          }
        }
      }
    } 
  </script>
</body>

</html>

templates/admin_pages/index.html
{% extends './admin_pages_base.html' %}

{% block profile_name_and_role %}
<span class="highlight" style="font-size: .7em;">
    {{ current_user }},&nbsp;
    {{ profile.profile_role }}
</span>
{% endblock profile_name_and_role %}

{% block profile_dropdown_links %}
<a href="{% url 'admin_pages:manage_user_profile' %}">User Profile</a>
<a href="{% url 'users:update_user' %}">User Account</a>
{% endblock profile_dropdown_links %}

{% block content %}

<style>
    .white-border :hover { border: 1px solid white; }
</style>

<div class="text-center">
    <p style="margin-top: 1%">Welcome back, {{ current_user }}.</p>
</div>

<div class="admin-menu shadow">
    <div class="typewriter">
        <div class="text-mono title" style="margin-left: 5%; font-weight: 600;">
            ./main_menu
        </div>
    </div>
    <div class="collapse-container shadow" style="color: #202223; padding-left: 26%;">
        <svg xmlns="http://www.w3.org/2000/svg" width="2.7em" height="2.7em" fill="currentColor" class="bi bi-bar-chart-steps" viewBox="0 0 16 16">
            <path d="M.5 0a.5.5 0 0 1 .5.5v15a.5.5 0 0 1-1 0V.5A.5.5 0 0 1 .5 0zM2 1.5a.5.5 0 0 1 .5-.5h4a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-4a.5.5 0 0 1-.5-.5v-1zm2 4a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-7a.5.5 0 0 1-.5-.5v-1zm2 4a.5.5 0 0 1 .5-.5h6a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-6a.5.5 0 0 1-.5-.5v-1zm2 4a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-7a.5.5 0 0 1-.5-.5v-1z"/>
        </svg>
        <span class="admin-title" style="font-size: 1.2em;">&nbsp;Metrics Display Options</span>
    </div>
    <div class="expand-content">
        <a class="admin-menu-item" href="{% url 'admin_pages:manage_pet_sales_opts' %}">
            {% load static %}
            <img src="{% static 'images/fa-dog.png' %}" width="8%" height="8%">
            <span class="admin-title" style="font-size: 1.2em;">Pet Sales</span>
        </a>
        <a class="admin-menu-item" href="{% url 'admin_pages:manage_product_sales_opts' %}">
            <svg xmlns="http://www.w3.org/2000/svg" width="3em" height="3em" fill="currentColor" class="bi bi-basket3-fill" viewBox="0 0 16 16">
                <path d="M5.757 1.071a.5.5 0 0 1 .172.686L3.383 6h9.234L10.07 1.757a.5.5 0 1 1 .858-.514L13.783 6H15.5a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5H.5a.5.5 0 0 1-.5-.5v-1A.5.5 0 0 1 .5 6h1.717L5.07 1.243a.5.5 0 0 1 .686-.172zM2.468 15.426.943 9h14.114l-1.525 6.426a.75.75 0 0 1-.729.574H3.197a.75.75 0 0 1-.73-.574z"/>
            </svg>
            <span class="admin-title" style="font-size: 1.2em;">Product Sales</span>
        </a>
        <a class="admin-menu-item" href="{% url 'admin_pages:manage_site_visits_opts' %}">
            <svg xmlns="http://www.w3.org/2000/svg" width="3em" height="3em" fill="currentColor" class="bi bi-bullseye" viewBox="0 0 16 16">
                <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                <path d="M8 13A5 5 0 1 1 8 3a5 5 0 0 1 0 10zm0 1A6 6 0 1 0 8 2a6 6 0 0 0 0 12z"/>
                <path d="M8 11a3 3 0 1 1 0-6 3 3 0 0 1 0 6zm0 1a4 4 0 1 0 0-8 4 4 0 0 0 0 8z"/>
                <path d="M9.5 8a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z"/>
            </svg>
            <span class="admin-title" style="font-size: 1.2em;">Site Visits</span>
        </a>
        <a class="admin-menu-item" href="{% url 'admin_pages:manage_pages_viewed_opts' %}">
            <svg xmlns="http://www.w3.org/2000/svg" width="3em" height="3em" fill="currentColor" class="bi bi-layers-fill" viewBox="0 0 16 16">
                <path d="M7.765 1.559a.5.5 0 0 1 .47 0l7.5 4a.5.5 0 0 1 0 .882l-7.5 4a.5.5 0 0 1-.47 0l-7.5-4a.5.5 0 0 1 0-.882l7.5-4z"/>
                <path d="m2.125 8.567-1.86.992a.5.5 0 0 0 0 .882l7.5 4a.5.5 0 0 0 .47 0l7.5-4a.5.5 0 0 0 0-.882l-1.86-.992-5.17 2.756a1.5 1.5 0 0 1-1.41 0l-5.17-2.756z"/>
              </svg>
            <span class="admin-title" style="font-size: 1.2em;">Pages Viewed</span>
        </a>
        <a class="admin-menu-item" href="{% url 'admin_pages:manage_users_opts' %}">
            <svg xmlns="http://www.w3.org/2000/svg" width="3em" height="3em" fill="currentColor" class="bi bi-people-fill" viewBox="0 0 16 16">
                <path d="M7 14s-1 0-1-1 1-4 5-4 5 3 5 4-1 1-1 1H7zm4-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
                <path fill-rule="evenodd" d="M5.216 14A2.238 2.238 0 0 1 5 13c0-1.355.68-2.75 1.936-3.72A6.325 6.325 0 0 0 5 9c-4 0-5 3-5 4s1 1 1 1h4.216z"/>
                <path d="M4.5 8a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5z"/>
            </svg>
            <span class="admin-title" style="font-size: 1.2em;">Users</span>
        </a>
        <a class="admin-menu-item" href="{% url 'admin_pages:manage_day_and_time_opts' %}">
            {% load static %}
            <svg xmlns="http://www.w3.org/2000/svg" width="3em" height="3em" fill="currentColor" class="bi bi-people-fill" viewBox="0 0 16 16">
                <path d="M7 14s-1 0-1-1 1-4 5-4 5 3 5 4-1 1-1 1H7zm4-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
                <path fill-rule="evenodd" d="M5.216 14A2.238 2.238 0 0 1 5 13c0-1.355.68-2.75 1.936-3.72A6.325 6.325 0 0 0 5 9c-4 0-5 3-5 4s1 1 1 1h4.216z"/>
                <path d="M4.5 8a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5z"/>
            </svg>
            <span class="admin-title" style="font-size: 1.2em;">Day & Time</span>
        </a>
    </div>
    <div class="collapse-container shadow" style="color: #202223; padding-left: 26%;">
        <svg xmlns="http://www.w3.org/2000/svg" width="2.7em" height="2.7em" fill="currentColor" class="bi bi-wrench" viewBox="0 0 16 16">
            <path d="M.102 2.223A3.004 3.004 0 0 0 3.78 5.897l6.341 6.252A3.003 3.003 0 0 0 13 16a3 3 0 1 0-.851-5.878L5.897 3.781A3.004 3.004 0 0 0 2.223.1l2.141 2.142L4 4l-1.757.364L.102 2.223zm13.37 9.019.528.026.287.445.445.287.026.529L15 13l-.242.471-.026.529-.445.287-.287.445-.529.026L13 15l-.471-.242-.529-.026-.287-.445-.445-.287-.026-.529L11 13l.242-.471.026-.529.445-.287.287-.445.529-.026L13 11l.471.242z"/>
        </svg>
        <span class="admin-title" style="font-size: 1.2em;">&nbsp;Configuration</span>
    </div>
    <div class="expand-content">
        <a class="admin-menu-item" href="{% url 'admin_pages:manage_site_look' %}">
            <svg xmlns="http://www.w3.org/2000/svg" width="3em" height="3em" fill="currentColor" class="bi bi-front" viewBox="0 0 16 16">
                <path d="M0 2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v2h2a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2v-2H2a2 2 0 0 1-2-2V2zm5 10v2a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1V6a1 1 0 0 0-1-1h-2v5a2 2 0 0 1-2 2H5z"/>
            </svg>
            <span class="admin-title" style="font-size: 1.2em;">Site Look</span>
        </a>
        <a class="admin-menu-item" href="{% url 'admin_pages:manage_home' %}">
            <svg xmlns="http://www.w3.org/2000/svg" width="3em" height="3em" fill="currentColor" class="bi bi-house-door-fill" viewBox="0 0 16 16">
                <path d="M6.5 14.5v-3.505c0-.245.25-.495.5-.495h2c.25 0 .5.25.5.5v3.5a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5z"/>
            </svg>
            <span class="admin-title" style="font-size: 1.2em;">Metrics Home</span>
        </a>
        <a class="admin-menu-item" href="{% url 'admin_pages:manage_users' %}">
            <svg xmlns="http://www.w3.org/2000/svg" width="3em" height="3em" fill="currentColor" class="bi bi-people-fill" viewBox="0 0 16 16">
                <path d="M7 14s-1 0-1-1 1-4 5-4 5 3 5 4-1 1-1 1H7zm4-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
                <path fill-rule="evenodd" d="M5.216 14A2.238 2.238 0 0 1 5 13c0-1.355.68-2.75 1.936-3.72A6.325 6.325 0 0 0 5 9c-4 0-5 3-5 4s1 1 1 1h4.216z"/>
                <path d="M4.5 8a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5z"/>
            </svg>
            <span class="admin-title" style="font-size: 1.2em;">Admins</span>
        </a>
    </div>

</div>
<script src='https://kit.fontawesome.com/a076d05399.js'></script>
<script>
    var collapse = document.getElementsByClassName("collapse-container");

    for (let i = 0; i < collapse.length; i++) {
        collapse[i].addEventListener("click", function() {
            this.classList.toggle("active");
            var content = this.nextElementSibling;
            if (content.style.display === "block") {
                content.style.display = "none";
            }
            else {
                content.style.display = "block";
            }
        });
    }
</script>
{% endblock content %}