admin_pages/urls.py
from django.urls import path, include
from . import views

app_name='admin_pages'

urlpatterns = [
    path('', views.admin_index, name='admin_index'),
    path('manage_site_look', views.manage_site_look, name='manage_site_look'),
    path('manage_home', views.manage_home, name='manage_home'),
    path('manage_users', views.manage_users, name='manage_users'),
    path('manage_user_profile', views.manage_user_profile, name='manage_user_profile'),

    # Metrics
    path('manage_pet_sales_opts', views.manage_pet_sales_opts, name='manage_pet_sales_opts'),
    path('manage_product_sales_opts', views.manage_product_sales_opts, name='manage_product_sales_opts'),
    path('manage_site_visits_opts', views.manage_site_visits_opts, name='manage_site_visits_opts'),
    path('manage_pages_viewed_opts', views.manage_pages_viewed_opts, name='manage_pages_viewed_opts'),
    path('manage_users_opts', views.manage_users_opts, name='manage_users_opts'),
    path('manage_day_and_time_opts', views.manage_day_and_time_opts, name='manage_day_and_time_opts'),
]

dashboard/urls.py
from django.contrib import admin
from django.contrib.auth import login, views as auth_views
from django.urls import path, include, reverse_lazy
from django.views.generic.base import TemplateView
from admin_pages import views as admin_views

urlpatterns = [
    path('', include('site_pages.urls')),
    path('admin_pages/', include('admin_pages.urls')),
    path('login/', auth_views.LoginView.as_view(
        	template_name='users/login.html'), name='login'),
    path('accounts/login/', auth_views.LoginView.as_view(
        	template_name='users/login.html'), name='login'),
    path('users/', include('users.urls')),
    path('robots.txt', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
]

site_pages/urls.py
from django.urls import path, include
from . import views

app_name='site_pages'

urlpatterns = [
    path('', views.index, name='index'),
]

users/urls.py
"""Defines url patterns for the users app."""

from django.urls import path, reverse, reverse_lazy
from django.contrib.auth import login, views as auth_views
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(
        	template_name='users/login.html'), name='login'),
	path('logout/', views.logout_view, name='logout'),
	path('register/', views.register, name='register'),
	path('update_user/', views.update_user, name='update_user'),
	path('confirm_delete_user/<int:user_id>', views.confirm_delete_user, name='confirm_delete_user'),
	path('delete_user/<int:user_id>', views.delete_user, name='delete_user'),

	path('reset_password/', auth_views.PasswordResetView.as_view(
			template_name='users/reset_password_email.html',
			email_template_name='users/reset_email_message.html',
			success_url=reverse_lazy('users:password_reset_complete'),
		), name='reset_password'),
	
	path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(
			template_name='users/reset_password_sent.html'), name='password_reset_done'),
	
	path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
			template_name='users/reset_password_confirm.html',
			success_url=reverse_lazy('users:password_reset_complete')
			), name='password_reset_confirm'),
	
	path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(
			template_name='users/reset_password_complete.html'), name='password_reset_complete')
]

users/models.py
from django.db import models

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.password_validation import validate_password

class SignUpForm(forms.ModelForm):
    first_name = forms.CharField(max_length=30, required=True)
    last_name  = forms.CharField(max_length=30, required=True)
    email      = forms.EmailField(max_length=254, required=True)
    username   = forms.CharField(max_length=30, required=True)
    password   = forms.CharField(max_length=30, required=True,
        widget=forms.PasswordInput,validators=[validate_password]
    )
    is_staff = forms.BooleanField(
        label='Admin Priveleges',
        required=False,
    )

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password', 'is_staff' )


class UpdateUserForm(forms.Form):
    first_name = forms.CharField(max_length=30, required=True)
    last_name  = forms.CharField(max_length=30, required=True)
    email      = forms.EmailField(max_length=254, required=True)

users/views.py
from django.shortcuts import render

from django.http import HttpResponse, HttpResponseRedirect

from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.models import User
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from admin_pages.models import UserProfile
from .forms import *

def logout_view(request):
    """Log the user out."""
    logout(request)
    return HttpResponseRedirect(reverse('login'))


@login_required
def register(request):
    """Register a new user."""
    if (request.method != 'POST'):
        form = SignUpForm()
    else:
        form = SignUpForm(data=request.POST)

        if (form.is_valid()):
            data = form.cleaned_data
            new_usr = User.objects.create_user(username=data['username'], email=data['email'],
                                                password=data['password'])
            fname = data['first_name']
            lname = data['last_name']
            new_usr.first_name = fname
            new_usr.last_name = lname
            new_usr.is_staff = data['is_staff']
            new_usr.save()
            new_usr.refresh_from_db()

            usr_profile = UserProfile(
                user=new_usr,
                profile_role='Hacker'
            )
            usr_profile.save()

            return HttpResponseRedirect(reverse('admin_pages:manage_users'))

    context = { 'form': form }
    return render(request, 'users/register.html', context)


@login_required
def update_user(request):
    user = User.objects.get(id=request.user.id)

    if request.method != 'POST':
        form = UpdateUserForm(initial={ 
            'first_name': user.first_name,
            'last_name': user.last_name,
            'email': user.email
         })
    else:
        form = UpdateUserForm(data=request.POST)
        if form.is_valid():
            data = form.cleaned_data
            fname = data['first_name']
            lname = data['last_name']
            email = data['email']

            user.first_name = fname
            user.last_name = lname
            user.email = email
            user.save()

            return HttpResponseRedirect(reverse('admin_pages:admin_index'))
   
    context = { 'form': form }
    return render(request, 'users/update_user.html', context)


@login_required
def confirm_delete_user(request, user_id):
    """Display a confirmation dialog view before deleting a user."""
    user = User.objects.get(id=user_id)

    context = { 'user': user }
    return render(request, 'users/confirm_delete_user.html', context)


@login_required
def delete_user(request, user_id):
    """Delete the user."""
    User.objects.get(id=user_id).delete()
    return HttpResponseRedirect(reverse('admin_pages:manage_users'))

templates/users/confirm_delete_user.html
{% extends "./users_base.html" %}

{% block content %}

<div class="login-container shadow">
	<div class="text-center"><h2>Delete User</h2></div>
	<p>
		Deleting user {{ user.username }} cannot be undone.
	</p>
	<div class="form-btn-container">
		<span class="space-left-sm">
			<button class="btn btn-primary" onclick="javascript:history.back();">
				Cancel
			</button>
		</span>
		<span class="space-left">
			<a href="{% url 'users:delete_user' user.id %}">
				<button class="btn btn-danger">
					Delete
				</button>
			</a>
		</span>
	</div>
</div>

{% endblock content %}

templates/users/login.html
{% extends './users_base.html' %}

{% block content %}
<div class="login-container shadow">

	<div class="title">
		<h2>Sign in to continue</h2>
	</div>

    <form action="{% url 'users:login' %}" method='post'>
        {% csrf_token %}
        {{ form.as_p }}

		<div class="form-btn-container">
			<div class="d-flex justify-content-center">
				<button class="btn btn-primary" type="submit"
					style="padding-left: 10%; padding-right: 10%;">
					Log in
				</button>
			</div>
		</div>

        <input type="hidden" name="next"
            value="{% url 'admin_pages:admin_index' %}" />
	</form>
	<br>
	Forgot your password?
	<a href="{% url 'users:reset_password' %}">Reset it here</a>.
</div>

{% endblock content %}

templates/users/register.html
{% extends './users_base.html' %}

{% block content %}

<style>
	ul { list-style: none; }
	li { color: red; }
</style>
<div class="d-flex justify-content-center" style="padding-top: 1%;">
    <a href="{% url 'admin_pages:manage_users' %}">
        <button class="btn btn-warning">&#60; Back to Menu</button>
    </a>
</div>
<div class="login-container shadow">
    <h2 class="text-center" style="margin-bottom: 4%;">
        Create Acccount
    </h2>
    <form method="post" action="{% url 'users:register' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary" name="submit">Register</button>
        <input type="hidden" name="next" value="{% url 'admin_pages:admin_index' %}">
    </form>
</div>
<br>

{% endblock content %}

templates/users/resent_email_message.html
{% load i18n %}{% autoescape off %}
   {% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}
   
{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}
  
{% translate "Thanks for using our site!" %}
 
{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

templates/users/reset_email_message.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

templates/users/reset_password.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href='https://fonts.googleapis.com/css?family=Muli' rel='stylesheet'>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
    </head>
    <body style="background-color: #E6E6E6;">
        <div class="center-container">
            <div class="form-container shadow">
                <div class="title">
                    <h2>Enter a new password</h2>
                </div>
                <p>
                    Please enter your new password twice so we
                    can verify that you typed it in correctly.
                </p>
    
                <form method='post'>
                    {% csrf_token %}
                    {{ form.as_p }}
                    <div class="form-btn-container text-center">
                        <button class="btn btn-primary" type="submit">
                            Save
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </body>
</html>

templates/users/reset_password_complete.html
{% extends './users_base.html' %}

{% block content %}
<div class="login-container shadow">
    <div class="title">
        <h2>Reset complete</h2>
    </div>  
    <p>
        After you have reset your password via the link
        sent to your email, you may log in again with
        your new password.
    </p>
    <div class="form-btn-container">
        <span class="space-left">
            <a href="{% url 'users:login' %}">
                <button class="btn btn-primary">
                    Log in
                </button>
            </a>
        </span>
    </div>
</div>
{% endblock content %}

templates/users/reset_password_confirm.html
{% extends "./users_base.html" %}
{% load i18n static %}

{% block extrastyle %}{{ block.super }}<link rel="stylesheet" type="text/css" href="{% static "admin/css/forms.css" %}">{% endblock %}
{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'admin:index' %}">{% translate 'Home' %}</a>
&rsaquo; {% translate 'Password reset confirmation' %}
</div>
{% endblock %}

{% block content %}

<style>
	ul { list-style: none; }
	li { color: red; }
</style>

{% if validlink %}

<div class="login-container shadow">
    <h2 class="text-center" style="margin-bottom: 4%;">
        Create Acccount
    </h2>
    <p>
        {% translate "Please enter your new password twice so we can verify you typed it in correctly." %}
    </p>
    <form method="post">{% csrf_token %}
        <fieldset class="module aligned">
            <input class="hidden" autocomplete="username" value="{{ form.user.get_username }}">
            <div class="form-row field-password1">
                {{ form.new_password1.errors }}
                <label for="id_new_password1">{% translate 'New password:' %}</label>
                {{ form.new_password1 }}
            </div>
            <div class="form-row field-password2">
                {{ form.new_password2.errors }}
                <label for="id_new_password2">{% translate 'Confirm password:' %}</label>
                {{ form.new_password2 }}
            </div>
            <div class="d-flex justify-content-center" style="margin-top: 3%;">
                <input class="btn btn-primary" type="submit" value="{% translate 'Change password' %}">
            </div>
        </fieldset>
        </form>
</div>
<br>


{% else %}

<p class="center-container">{% translate "The password reset link was invalid, possibly because it has already been used.  Please request a new password reset." %}</p>

{% endif %}

{% endblock %}

templates/users/reset_password_email.html
{% extends './users_base.html' %}

{% block content %}
<div class="login-container shadow">

    <div class="title">
        <h2>Reset Password</h2>
    </div>
    <p>
        Forgotten your password?<br>
        Enter your email address below, and we'll email instructions
        for setting a new one.
    </p>
    <form method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <div class="form-btn-container">
            <span class="space-left-sm">
				<button class="btn btn-primary" type="submit">
					Send
				</button>
			</span>
			<span class="space-left">
                <button class="btn btn-danger" onclick="javascript:history.back();">
				    Cancel
			    </button>
            </span>
        </div>
    </form>
</div>
{% endblock content %}

templates/users/reset_password_sent.html
{% extends './users_base.html' %}

{% block content %}
<div class="center-container">
    <div class="form-container shadow">
        <div class="title">
            <h2>Password reset sent</h2>
        </div>
        <p>
            We’ve emailed you instructions for setting your password,
            if an account exists with the email you entered. You should
            receive them shortly.
        </p>
        <p>
            If you don’t receive an email, please make sure you’ve 
            entered the address you registered with, and check your spam folder.
        </p>
    </div>
</div>
{% endblock content %}

templates/users/update_user.html
{% extends './users_base.html' %}

{% block content %}

<style>
	ul { list-style: none; }
	li { color: red; }
</style>
<div class="login-container shadow">
    <h2 class="text-center" style="margin-bottom: 4%;">
        Account Settings
    </h2>
    <div class="d-flex justify-content-center" style="margin-bottom: 5%;">
        <a href="{% url 'users:reset_password' %}">
            <button class="btn btn-outline-secondary">
                Update my password
            </button>
        </a>
    </div>
    <form method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <div class="form-btn-container">
            <div class="d-flex justify-content-center">
                <button class="btn btn-primary" type="submit"
                    style="padding-left: 30%; padding-right: 30%;">
                    Save
                </button>
            </div>
        </div>
    </form>
</div>
<br>

{% endblock content %}

templates/users/users_base.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href='https://fonts.googleapis.com/css?family=Muli' rel='stylesheet'>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">

  <style>
    body {
        background-color: #E6E6E6;
    }

    ul { list-style: none; }
	li { color: red; }

    @media only screen
    and (min-width : 1320px) {

        input {
            width: 18em;
        }
    }

    @media only screen
    and (max-width: 1319px) and (min-width: 690px) {

        label {
            font-size: 1em;
        }

        input {
            width: 18em;
        }

        textarea {
            width: 18em;
        }

        .login-container {
            width: 60%;
        }
    }

    @media only screen
    and (max-width: 689px) and (min-width: 470px) {

        label {
            font-size: 1em;
        }

        input {
            width: 18em;
        }

        textarea {
            width: 18em;
        }

        .login-container {
            width: 90%;
        }
    }

    @media only screen
    and (max-width: 469px){

        label {
            font-size: 0.9em;
        }

        input {
            width: 12em;
        }

        textarea {
            width: 12em;
        }

        .login-container {
            width: 95%;
        }
    }
  </style>
</head>

<body>
<nav class="navbar navbar-expand-md static-top" style="background-color: #E0E0E0;">
  <div class="container">
    <a class="navbar-brand" href="{% url 'site_pages:index' %}">
      {% load static %}
      <img src="{% static 'nav_image/nav_image.png' %}"
        alt="Navigation icon" style="{{ navigation_img_size }}">
    </a>
  </div>
</nav>

{% block content %} {% endblock content %}

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>

</html>